server:
  port: 8080

spring:
  datasource:
    #数据源的基本配置
    username: root
    password: silvercrow@6133
    url: jdbc:mysql://silvercrow.online:3306/surfshark?useUnicode=true&characterEncoding=utf-8&serverTimezone = UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM dual;


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    console: (%msg%n%n){blue}


#xxl-job
xxl:
  job:
    admin:
      addresses: http://silvercrow.online:8088
    executor:
      appname: surfshark-job
      ip: 113.246.243.115
      port: 9998
      logpath: /data/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:
