server:
  port: 8080

spring:
  datasource:
    #数据源的基本配置
    username: root
    password: silvercrow@6133
    url: jdbc:mysql://49.233.207.137:3306/surfshark?useUnicode=true&characterEncoding=utf-8&serverTimezone = UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM dual;
      max-active: 10
      initial-size: 5
      min-idle: 2

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.zxs.surfshark.beans
  configuration:
    map-underscore-to-camel-case: true